import { cookies } from 'next/headers';

export const dynamic = 'force-dynamic';

export default async function InsightsPage() {
    let insights = [];
    let error = null;

    try {
        // 1. Extract the token from the secure Next.js Server Cookie
        const cookieStore = await cookies();
        const token = cookieStore.get('kh_os_token')?.value;

        if (!token) {
            throw new Error("Unauthorized: Please log in to view your insights.");
        }

        // 2. Attach it to the FastAPI request
        const aiServiceUrl = process.env.NEXT_PUBLIC_AI_SERVICE_URL || 'http://localhost:8000';
        const res = await fetch(`${aiServiceUrl}/insights`, {
            cache: 'no-store',
            headers: {
                'Authorization': `Bearer ${token}`, // 🔒 Secure payload!
                'Content-Type': 'application/json'
            }
        });

        if (!res.ok) {
            if (res.status === 401) throw new Error("Your session has expired. Please log in again.");
            throw new Error("Failed to fetch from AI Service");
        }

        const data = await res.json();
        insights = data.insights;
    } catch (err: any) {
        error = err.message;
    }

    return (
        <div className="max-w-4xl mx-auto mt-8 px-4 pb-12">
            <div className="mb-10">
                <div className="inline-flex items-center justify-center px-4 py-1.5 mb-4 rounded-full bg-primary/10 border border-primary/20 text-primary text-xs font-semibold uppercase tracking-wider">
                    Autonomous Brain
                </div>
                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-3">
                    <span className="bg-clip-text text-transparent bg-gradient-to-r from-textMain to-zinc-500">
                        Intelligence Feed
                    </span>
                </h1>
                <p className="text-lg text-textMuted max-w-2xl">Real-time career roadmaps and active productivity coaching generated by your Gemini engine.</p>
            </div>

            {error && (
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-4 rounded-xl mb-8 flex items-start">
                    <svg className="w-5 h-5 mr-3 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                    </svg>
                    <span>Unable to connect to the AI Service Brain: {error}</span>
                </div>
            )}

            <div className="grid gap-6">
                {insights.length === 0 && !error ? (
                    <div className="bg-surface/30 border border-zinc-800/50 border-dashed rounded-3xl flex flex-col items-center justify-center py-20 text-center">
                        <div className="w-16 h-16 rounded-full bg-zinc-800/50 flex items-center justify-center mb-4">
                            <span className="text-3xl">💤</span>
                        </div>
                        <h3 className="text-xl font-bold text-textMain mb-2">No insights generated yet</h3>
                        <p className="text-textMuted max-w-sm">Complete a task in your workspace to wake up the AI and receive your first coaching insight!</p>
                    </div>
                ) : (
                    insights.map((insight: any) => {
                        // Fallback to career_roadmap for older test data
                        const type = insight.type || "career_roadmap";
                        const isRoadmap = type === "career_roadmap";

                        return (
                            <div
                                key={insight._id}
                                className={`bg-surface/80 backdrop-blur-sm border rounded-3xl p-6 md:p-8 shadow-xl transition-all duration-300 ${isRoadmap ? 'border-zinc-800/60 hover:border-primary/50' : 'border-zinc-800/60 hover:border-success/50'
                                    }`}
                            >
                                <div className="flex flex-col md:flex-row md:justify-between md:items-start mb-6 gap-4">
                                    <div>
                                        <h3 className="text-xl font-bold text-textMain flex items-center tracking-tight">
                                            {isRoadmap ? (
                                                <><span className="mr-2 text-2xl">🗺️</span> Career Roadmap Generated</>
                                            ) : (
                                                <><span className="mr-2 text-2xl">🎯</span> Productivity Coach</>
                                            )}
                                        </h3>

                                        {/* Dynamic Badges based on event type */}
                                        <div className="flex flex-wrap gap-2 mt-3">
                                            {isRoadmap ? (
                                                <>
                                                    <span className="text-xs font-semibold px-3 py-1 bg-primary/10 text-primary border border-primary/20 rounded-full shadow-sm">
                                                        Role: {insight.role || "Developer"}
                                                    </span>
                                                    <span className="text-xs font-medium px-3 py-1 bg-zinc-800/80 text-zinc-400 border border-zinc-700/50 rounded-full">
                                                        User: {insight.userId.substring(0, 8)}...
                                                    </span>
                                                </>
                                            ) : (
                                                <>
                                                    <span className="text-xs font-semibold px-3 py-1 bg-success/10 text-success border border-success/20 rounded-full shadow-sm">
                                                        Task: {insight.task}
                                                    </span>
                                                    <span className="text-xs font-medium px-3 py-1 bg-zinc-800/80 text-zinc-400 border border-zinc-700/50 rounded-full">
                                                        Goal: {insight.goal}
                                                    </span>
                                                </>
                                            )}
                                        </div>
                                    </div>

                                    <div className="text-xs text-zinc-500 font-mono bg-background/50 px-3 py-1.5 rounded-lg border border-zinc-800/50 flex-shrink-0 self-start">
                                        ID: {insight._id.substring(0, 8)}
                                    </div>
                                </div>

                                <div className={`relative overflow-hidden rounded-2xl p-6 border ${isRoadmap ? 'bg-background/40 border-zinc-800/50' : 'bg-success/5 border-success/10'
                                    }`}>
                                    {/* Subtle gradient glow inside insight box */}
                                    <div className={`absolute top-0 right-0 w-32 h-32 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2 pointer-events-none ${isRoadmap ? 'bg-primary/5' : 'bg-success/5'}`}></div>

                                    <div className="flex items-center mb-3 relative z-10">
                                        <span className={`w-2 h-2 rounded-full mr-2 ${isRoadmap ? 'bg-primary animate-pulse' : 'bg-success'}`}></span>
                                        <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-widest">
                                            Gemini Analysis
                                        </span>
                                    </div>
                                    <p className="text-textMain leading-relaxed text-sm relative z-10">
                                        {insight.ai_summary}
                                    </p>
                                </div>
                            </div>
                        );
                    })
                )}
            </div>
        </div>
    );
}
