const { compileFromFile } = require('json-schema-to-typescript');
const fs = require('fs');

const schemaPath = process.argv[2];
const tsOutPath = process.argv[3];

async function generate() {
    const tsCode = await compileFromFile(schemaPath, {
        additionalProperties: false,
        bannerComment: '/* ESLint-disable */\n/**\n* This file was automatically generated by Bazel.\n* DO NOT MODIFY IT BY HAND.\n*/'
    });
    fs.writeFileSync(tsOutPath, tsCode);
}

generate().catch(err => {
    console.error(err);
    process.exit(1);
});
