/* ESLint-disable */
/**
 * This file was automatically generated by Bazel.
 * DO NOT MODIFY IT BY HAND.
 */

export interface TaskCompletedEvent {
  eventId: string;
  timestamp: string;
  data: {
    userId: string;
    goalTitle: string;
    taskTitle: string;
  };
}
