/* ESLint-disable */
/**
 * This file was automatically generated by Bazel.
 * DO NOT MODIFY IT BY HAND.
 */

export interface UserCreatedEvent {
  eventId: string;
  timestamp: string;
  data: {
    userId: string;
    email: string;
    role: string;
  };
}
